apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-rwx
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 40Gi
