apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rookceph-install
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  source:
    repoURL: https://github.com/akshtshrma24/homelab.git
    targetRevision: master
    path: k8s-infra/kustomize/rookceph/install
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
