apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-tools
  namespace: rook-ceph
  labels:
    app: rook-ceph-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-tools
  template:
    metadata:
      labels:
        app: rook-ceph-tools
    spec:
      serviceAccountName: rook-ceph-system
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: rook-ceph-tools
          image: rook/ceph:v1.14.11
          command:
            - /tini
          args:
            - -g
            - --
            - /usr/local/bin/toolbox.sh
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
